allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  esbuild: false
  msgpackr-extract: set this to true or false
  prisma: false
  workerd: set this to true or false
